# https://travis-ci.org/#!/phlax/pyliff
sudo: false
language: python
python:
  - 2.7
cache:
  directories:
    - $HOME/.cache/pip
    - docs/_build
install:
  - pip install --upgrade pip
  - pip install -r requirements/test.txt
  - pip install .
script:
  - py.test --cov=. -vv
  - flake8 . --config=.flake8
after_success:
  - coveralls
